### ISSUE TITLE
T02 Phomemo seems incompatible - printing does not occur

### ISSUE THREAD

**Issue by stubkan** [vivier/phomemo-tools#18]
I acquired a little T02, hoping to replace my large thermal printer with it. I assumed from this repo that I would be able to use it,  however it appears this may not be the case.

I have Ubuntu 22.04, and have cups, pybluez already installed on my system, no problems.  Made and installed the cups driver from this repo, then went and paired the T02 device in bluetooth settings.  But when I get to the Printer window, there is no T02 to be seen.  I confirm the Phomemo driver is installed, as I can add a CUPS-BRK driver using the Phomemo M02 template, and tried to print to the T02 using that, but every time I print, it says it printed successfully then nothing at all happens.

Either I set up something wrongly, or the T02 is not supported?

Confirmed I have the prequisites; 
cups is already the newest version (2.4.1op1-1ubuntu4.7).
Requirement already satisfied: pybluez in /usr/lib/python3/dist-packages (0.23)

The T02 does not show up in the printer devices when I try to add it here, as per the instructions;

![image](https://github.com/vivier/phomemo-tools/assets/34361592/c7e63b3c-477a-41ec-b000-79d5261f3b67)

So I tried to manually add it anyway, by creating a generic CUPS-BRF driver for M02 and named it T02;

![image](https://github.com/vivier/phomemo-tools/assets/34361592/1bd6385d-875f-48b8-be21-1e5bc625c5c5)

This is the added printer info from localhost:631 CUPS interface;

![image](https://github.com/vivier/phomemo-tools/assets/34361592/95bb4212-df98-408b-a170-1ac31fa7e87a)

Here is my cups access log;

```
localhost - - [03/Nov/2023:00:00:02 +0000] "POST / HTTP/1.1" 200 349 Create-Printer-Subscriptions successful-ok
localhost - - [03/Nov/2023:00:00:02 +0000] "POST / HTTP/1.1" 200 176 Create-Printer-Subscriptions successful-ok
localhost - - [03/Nov/2023:00:02:34 +0000] "POST / HTTP/1.1" 200 155 Cancel-Subscription successful-ok
localhost - - [03/Nov/2023:00:04:49 +0000] "POST / HTTP/1.1" 200 276 Create-Printer-Subscriptions successful-ok
localhost - - [03/Nov/2023:00:04:52 +0000] "POST / HTTP/1.1" 401 147 CUPS-Get-Devices successful-ok
localhost - cups-pk-helper [03/Nov/2023:00:04:52 +0000] "POST / HTTP/1.1" 200 1549 CUPS-Get-Devices -
localhost - cups-pk-helper [03/Nov/2023:00:04:52 +0000] "POST / HTTP/1.1" 200 222 CUPS-Get-Devices -
localhost - - [03/Nov/2023:00:05:54 +0000] "POST / HTTP/1.1" 401 147 CUPS-Get-Devices successful-ok
localhost - cups-pk-helper [03/Nov/2023:00:05:54 +0000] "POST / HTTP/1.1" 200 1549 CUPS-Get-Devices -
localhost - cups-pk-helper [03/Nov/2023:00:05:54 +0000] "POST / HTTP/1.1" 200 222 CUPS-Get-Devices -
localhost - - [03/Nov/2023:00:06:26 +0000] "GET /admin/conf/cupsd.conf HTTP/1.1" 401 0 - -
localhost - stubkan [03/Nov/2023:00:06:26 +0000] "GET /admin/conf/cupsd.conf HTTP/1.1" 200 4690 - -
localhost - - [03/Nov/2023:00:06:26 +0000] "GET /admin/conf/cupsd.conf HTTP/1.1" 401 0 - -
localhost - cups-pk-helper [03/Nov/2023:00:06:26 +0000] "GET /admin/conf/cupsd.conf HTTP/1.1" 200 4690 - -
localhost - - [03/Nov/2023:00:07:47 +0000] "POST / HTTP/1.1" 401 147 CUPS-Get-Devices successful-ok
localhost - cups-pk-helper [03/Nov/2023:00:07:47 +0000] "POST / HTTP/1.1" 200 1549 CUPS-Get-Devices -
localhost - cups-pk-helper [03/Nov/2023:00:07:47 +0000] "POST / HTTP/1.1" 200 222 CUPS-Get-Devices -
localhost - cups-pk-helper [03/Nov/2023:00:07:52 +0000] "POST / HTTP/1.1" 200 1549 CUPS-Get-Devices -
localhost - cups-pk-helper [03/Nov/2023:00:07:52 +0000] "POST / HTTP/1.1" 200 222 CUPS-Get-Devices -
localhost - - [03/Nov/2023:00:07:53 +0000] "POST / HTTP/1.1" 200 5462486 CUPS-Get-PPDs -
localhost - - [03/Nov/2023:00:08:10 +0000] "POST / HTTP/1.1" 200 8498 CUPS-Get-PPD -
localhost - - [03/Nov/2023:00:08:41 +0000] "POST /admin/ HTTP/1.1" 401 8549 CUPS-Add-Modify-Printer successful-ok
localhost - stubkan [03/Nov/2023:00:08:41 +0000] "POST /admin/ HTTP/1.1" 200 8549 CUPS-Add-Modify-Printer successful-ok
localhost - - [03/Nov/2023:00:08:41 +0000] "POST /admin/ HTTP/1.1" 401 166 Resume-Printer successful-ok
localhost - cups-pk-helper [03/Nov/2023:00:08:41 +0000] "POST /admin/ HTTP/1.1" 200 166 Resume-Printer successful-ok
localhost - cups-pk-helper [03/Nov/2023:00:08:41 +0000] "POST /admin/ HTTP/1.1" 200 166 CUPS-Accept-Jobs successful-ok
localhost - cups-pk-helper [03/Nov/2023:00:08:41 +0000] "POST /admin/ HTTP/1.1" 200 166 CUPS-Set-Default successful-ok
localhost - cups-pk-helper [03/Nov/2023:00:08:41 +0000] "POST /admin/ HTTP/1.1" 200 188 CUPS-Add-Modify-Printer successful-ok
localhost - cups-pk-helper [03/Nov/2023:00:08:41 +0000] "POST /admin/ HTTP/1.1" 200 203 CUPS-Add-Modify-Printer successful-ok
localhost - - [03/Nov/2023:00:08:44 +0000] "POST /printers/Phomemo-T02 HTTP/1.1" 200 415 Print-Job successful-ok
localhost - - [03/Nov/2023:00:08:44 +0000] "POST / HTTP/1.1" 200 365 Create-Printer-Subscriptions successful-ok
localhost - - [03/Nov/2023:00:11:46 +0000] "POST / HTTP/1.1" 200 365 Create-Printer-Subscriptions successful-ok
localhost - - [03/Nov/2023:00:11:46 +0000] "POST / HTTP/1.1" 200 365 Create-Printer-Subscriptions successful-ok
localhost - - [03/Nov/2023:00:17:02 +0000] "POST /printers/Phomemo-T02 HTTP/1.1" 200 316 Create-Job successful-ok
localhost - - [03/Nov/2023:00:17:02 +0000] "POST /printers/Phomemo-T02 HTTP/1.1" 200 274339 Send-Document successful-ok
localhost - - [03/Nov/2023:00:18:33 +0000] "POST /printers/Phomemo-T02 HTTP/1.1" 200 316 Create-Job successful-ok
localhost - - [03/Nov/2023:00:18:33 +0000] "POST /printers/Phomemo-T02 HTTP/1.1" 200 274336 Send-Document successful-ok
localhost - - [03/Nov/2023:00:22:23 +0000] "POST /printers/Phomemo-T02 HTTP/1.1" 200 316 Create-Job successful-ok
localhost - - [03/Nov/2023:00:22:23 +0000] "POST /printers/Phomemo-T02 HTTP/1.1" 200 274336 Send-Document successful-ok
localhost - - [03/Nov/2023:00:24:01 +0000] "POST / HTTP/1.1" 200 155 Cancel-Subscription successful-ok
localhost - - [03/Nov/2023:00:24:01 +0000] "POST / HTTP/1.1" 200 365 Create-Printer-Subscriptions successful-ok
localhost - - [03/Nov/2023:00:24:01 +0000] "POST / HTTP/1.1" 200 155 Cancel-Subscription successful-ok
localhost - - [03/Nov/2023:00:24:01 +0000] "POST / HTTP/1.1" 200 365 Create-Printer-Subscriptions successful-ok
localhost - - [03/Nov/2023:00:24:22 +0000] "POST / HTTP/1.1" 200 155 Cancel-Subscription successful-ok
localhost - - [03/Nov/2023:00:24:22 +0000] "POST / HTTP/1.1" 200 365 Create-Printer-Subscriptions successful-ok
localhost - - [03/Nov/2023:00:24:22 +0000] "POST / HTTP/1.1" 200 155 Cancel-Subscription successful-ok
localhost - - [03/Nov/2023:00:24:22 +0000] "POST / HTTP/1.1" 200 365 Create-Printer-Subscriptions successful-ok
localhost - - [03/Nov/2023:00:24:34 +0000] "POST /jobs/ HTTP/1.1" 200 142 Restart-Job successful-ok
localhost - - [03/Nov/2023:00:25:20 +0000] "POST /jobs/ HTTP/1.1" 200 157 Cancel-Job successful-ok
localhost - - [03/Nov/2023:00:25:27 +0000] "POST /jobs/ HTTP/1.1" 200 157 Cancel-Job successful-ok
localhost - - [03/Nov/2023:00:25:32 +0000] "POST /jobs/ HTTP/1.1" 200 157 Cancel-Job successful-ok
localhost - - [03/Nov/2023:00:25:53 +0000] "POST / HTTP/1.1" 200 155 Cancel-Subscription successful-ok
localhost - - [03/Nov/2023:00:25:53 +0000] "POST / HTTP/1.1" 200 365 Create-Printer-Subscriptions successful-ok
localhost - - [03/Nov/2023:00:25:53 +0000] "POST / HTTP/1.1" 200 155 Cancel-Subscription successful-ok
localhost - - [03/Nov/2023:00:25:53 +0000] "POST / HTTP/1.1" 200 365 Create-Printer-Subscriptions successful-ok
localhost - - [03/Nov/2023:00:25:54 +0000] "POST / HTTP/1.1" 200 155 Cancel-Subscription successful-ok
localhost - - [03/Nov/2023:00:25:54 +0000] "POST / HTTP/1.1" 200 365 Create-Printer-Subscriptions successful-ok
localhost - - [03/Nov/2023:00:25:54 +0000] "POST / HTTP/1.1" 200 155 Cancel-Subscription successful-ok
localhost - - [03/Nov/2023:00:25:54 +0000] "POST / HTTP/1.1" 200 365 Create-Printer-Subscriptions successful-ok
localhost - - [03/Nov/2023:00:25:54 +0000] "POST / HTTP/1.1" 200 155 Cancel-Subscription successful-ok
localhost - - [03/Nov/2023:00:25:54 +0000] "POST / HTTP/1.1" 200 365 Create-Printer-Subscriptions successful-ok
localhost - - [03/Nov/2023:00:25:54 +0000] "POST / HTTP/1.1" 200 155 Cancel-Subscription successful-ok
localhost - - [03/Nov/2023:00:25:54 +0000] "POST / HTTP/1.1" 200 365 Create-Printer-Subscriptions successful-ok
localhost - - [03/Nov/2023:00:25:59 +0000] "POST /jobs/ HTTP/1.1" 200 157 Cancel-Job successful-ok
localhost - - [03/Nov/2023:00:26:00 +0000] "POST / HTTP/1.1" 200 155 Cancel-Subscription successful-ok
localhost - - [03/Nov/2023:00:26:00 +0000] "POST / HTTP/1.1" 200 365 Create-Printer-Subscriptions successful-ok
localhost - - [03/Nov/2023:00:26:00 +0000] "POST / HTTP/1.1" 200 155 Cancel-Subscription successful-ok
localhost - - [03/Nov/2023:00:26:00 +0000] "POST / HTTP/1.1" 200 365 Create-Printer-Subscriptions successful-ok
localhost - - [03/Nov/2023:00:27:42 +0000] "POST /printers/Phomemo-T02 HTTP/1.1" 200 316 Create-Job successful-ok
localhost - - [03/Nov/2023:00:27:42 +0000] "POST /printers/Phomemo-T02 HTTP/1.1" 200 367503 Send-Document successful-ok
localhost - - [03/Nov/2023:00:27:54 +0000] "POST / HTTP/1.1" 200 276 Create-Printer-Subscriptions successful-ok
localhost - - [03/Nov/2023:00:27:56 +0000] "POST / HTTP/1.1" 401 147 CUPS-Get-Devices successful-ok
localhost - cups-pk-helper [03/Nov/2023:00:27:56 +0000] "POST / HTTP/1.1" 200 1549 CUPS-Get-Devices -
localhost - cups-pk-helper [03/Nov/2023:00:27:56 +0000] "POST / HTTP/1.1" 200 222 CUPS-Get-Devices -
localhost - - [03/Nov/2023:00:34:00 +0000] "POST /printers/Phomemo-T02 HTTP/1.1" 200 415 Print-Job successful-ok
localhost - - [03/Nov/2023:00:35:48 +0000] "POST /admin/ HTTP/1.1" 200 66 - -
localhost - - [03/Nov/2023:00:35:48 +0000] "POST / HTTP/1.1" 401 75 CUPS-Get-Devices successful-ok
localhost - - [03/Nov/2023:00:35:48 +0000] "POST /admin/ HTTP/1.1" 200 1909 - -
localhost - - [03/Nov/2023:00:35:53 +0000] "POST /admin/ HTTP/1.1" 200 60 - -
localhost - - [03/Nov/2023:00:35:53 +0000] "POST / HTTP/1.1" 401 91 CUPS-Get-Devices successful-ok
localhost - - [03/Nov/2023:00:35:53 +0000] "POST /admin/ HTTP/1.1" 401 60 - -
localhost - - [03/Nov/2023:00:35:53 +0000] "POST /admin/ HTTP/1.1" 200 60 - -
localhost - stubkan [03/Nov/2023:00:35:58 +0000] "POST /admin/ HTTP/1.1" 200 60 - -
localhost - - [03/Nov/2023:00:35:58 +0000] "POST / HTTP/1.1" 401 91 CUPS-Get-Devices successful-ok
localhost - stubkan [03/Nov/2023:00:35:58 +0000] "POST / HTTP/1.1" 200 1493 CUPS-Get-Devices -
localhost - stubkan [03/Nov/2023:00:35:58 +0000] "POST /admin/ HTTP/1.1" 200 3360 - -
localhost - - [03/Nov/2023:00:36:41 +0000] "POST / HTTP/1.1" 401 147 CUPS-Get-Devices successful-ok
localhost - cups-pk-helper [03/Nov/2023:00:36:41 +0000] "POST / HTTP/1.1" 200 1549 CUPS-Get-Devices -
localhost - cups-pk-helper [03/Nov/2023:00:36:41 +0000] "POST / HTTP/1.1" 200 222 CUPS-Get-Devices -
localhost - - [03/Nov/2023:00:36:49 +0000] "POST / HTTP/1.1" 200 155 Cancel-Subscription successful-ok
localhost - - [03/Nov/2023:00:43:29 +0000] "POST / HTTP/1.1" 200 186 Renew-Subscription successful-ok
```

and the error log with debug turned on

```
E [03/Nov/2023:00:00:02 +0000] Unknown directive JobPrivateAccess on line 122 of /etc/cups/cupsd.conf.
E [03/Nov/2023:00:00:02 +0000] Unknown directive JobPrivateValues on line 123 of /etc/cups/cupsd.conf.
E [03/Nov/2023:00:00:02 +0000] Unknown directive SubscriptionPrivateAccess on line 124 of /etc/cups/cupsd.conf.
E [03/Nov/2023:00:00:02 +0000] Unknown directive SubscriptionPrivateValues on line 125 of /etc/cups/cupsd.conf.
E [03/Nov/2023:00:04:52 +0000] [cups-deviced] PID 49458 (phomemo) stopped with status 1!
E [03/Nov/2023:00:05:54 +0000] [cups-deviced] PID 49520 (phomemo) stopped with status 1!
E [03/Nov/2023:00:07:47 +0000] [cups-deviced] PID 49654 (phomemo) stopped with status 1!
E [03/Nov/2023:00:07:52 +0000] [cups-deviced] PID 49688 (phomemo) stopped with status 1!
E [03/Nov/2023:00:27:56 +0000] [cups-deviced] PID 53476 (phomemo) stopped with status 1!
E [03/Nov/2023:00:35:59 +0000] [cups-deviced] PID 54411 (phomemo) stopped with status 1!
E [03/Nov/2023:00:36:41 +0000] [cups-deviced] PID 54489 (phomemo) stopped with status 1!
```

**Comment by stubkan** [comment]
@daig0rian @vivier @taylorjdlee 

Sorry to ping, but is this repo going to be unsupported and new devices are not going to be added?  T02 is supposedly compatible since it has the same protocols as M02 - but no matter what I try, it does not work.

**Comment by stubkan** [comment]
Some futher info, just in case.

CUPS driver is installed, I had difficulty getting pybluez due to distro issues but got it working in the end thanks to this guy https://stackoverflow.com/questions/75262991/i-found-the-way-to-install-pybluez-on-ubuntu-22-04

![image](https://github.com/vivier/phomemo-tools/assets/34361592/4709ebee-d565-4a67-8026-55585a3f47f8)

![image](https://github.com/vivier/phomemo-tools/assets/34361592/ce727f11-93a3-4611-adc2-4e634e7ae711)

**Comment by darkmattercoder** [comment]
I have to correct my previous statement. The auto discovery works, now that I understood that cups reads some stdout print string from the bluetooth scan function to show the found printer. when we changed that to also take T02 as valid name into account, the auto discovery works as well.

**Comment by stubkan** [comment]
@darkmattercoder 

The installation method for pybluez had to be done differently for me, also on Ubuntu, however it SEEMS to be installed, although under a different name - are you saying this is broken and this is potentially a reason why I can't get the T02 to work on my end?  I have installed python3-bluez instead of pybluez?

**Comment by vivier** [comment]
Hi, I've merged yesterday a pull request https://github.com/vivier/phomemo-tools/pull/20 from @klonfish that replace PyBluez by socket.
Does it fix your problem?
I don't have a lot of time to test and develop, but generally I try to merge the pull request I receive.

**Comment by darkmattercoder** [comment]
Yes, @klonfish and I did test that together, I will issue a follow up pull request which takes care of the name discovering during bt scanning in a couple of days.

**Comment by nww02** [comment]
Hi,  I managed to get the T02 talking to Linux Mint by copying the filter and drv files into /usr/share/cups/.....  and chowning them to root.   I paired to the bluetooth printer and then added the printer as bluetooth://MACADDRESS ... That worked perfectly.

I can print to the printer, BUT it does a loooooong linefeed before each print, effectively skipping about 3 labels-worth.   

Tried printing from the app and it works fine,  but for some reason Linux just adds a load of whitespace before the print.   Any idea why this might be happening?

**Comment by darkmattercoder** [comment]
Did you notice the pr https://github.com/vivier/phomemo-tools/pull/21 ? 
We improved the driver significantly in there. The only issue that I still cannot fix is that if you print large amounts of data, the printer suddenly stops printing and feeds before the print is completed.

However the overall detection over bluetooth, and using in cups has been improved in the pr.

**Comment by vivier** [comment]
Please check the latest version in git repo.

**Comment by nww02** [comment]
I'm not a GitHub power user. I just converted to Linux as a desktop last year. I'm not up to compiling things from scratch, really.  I just needeed a driver so found a link to an rpm and muddled my way through copying the files out.   

The driver works with some file wrangling,  but would be great if there was a version that had the T02 and was a.deb release ready to install for noobs like me :)   

I'm just happy it works!   Awesome work reverse engineering the protocol!

**Comment by Buom01** [comment]
![2024-07-02-16-18-18-164](https://github.com/vivier/phomemo-tools/assets/1537208/c16bcd31-6653-4314-94ab-5b3800ba5a8d)

Hello,

OS: CachyOS Linux x86_64
Kernel: Linux 6.6.35-1-cachyos-lts
Using Plasma

Steps I've done:
1. Pair the printer, just pair. (T02)
2. Install phomemo-tools-git
3. Restart cups (systemctl restart cups)
4. Open printers ("Configuration de l'impression" or probably "Configure printers")
5. Add
6. It should be listed, just select, next, next, ...

I've also tested a simple icon to confirm it works.

Thanks so much.

**Comment by vivier** [comment]
Thank you @Buom01 for the information

**Comment by brunetton** [comment]
> ![2024-07-02-16-18-18-164](https://private-user-images.githubusercontent.com/1537208/345071022-c16bcd31-6653-4314-94ab-5b3800ba5a8d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NDcxNDMsIm5iZiI6MTczNTY0Njg0MywicGF0aCI6Ii8xNTM3MjA4LzM0NTA3MTAyMi1jMTZiY2QzMS02NjUzLTQzMTQtOTRhYi01YjM4MDBiYTVhOGQuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMzFUMTIwNzIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTFmMjJmYzM4NWM1M2VhZThmNzc4OWY5YTIzMWEwNTY2NjQxZDc3MmMzZGY5ZGY5YTY3ZjU1NjVlNzQ3N2JlZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.E3216Rzz8PrJIVGOP4JcvZwZhQlhFA15ltKzCF660x0)
> 
> Hello,
> 
> OS: CachyOS Linux x86_64 Kernel: Linux 6.6.35-1-cachyos-lts Using Plasma
> 
> Steps I've done:
> 
> 1. Pair the printer, just pair. (T02)
> 2. Install phomemo-tools-git
> 3. Restart cups (systemctl restart cups)
> 4. Open printers ("Configuration de l'impression" or probably "Configure printers")
> 5. Add
> 6. It should be listed, just select, next, next, ...
> 
> I've also tested a simple icon to confirm it works.
> 
> Thanks so much.

Thank you for this, I tried but didn't succeeded printing from UI (only command line). Details here in #30 

Did you experienced similar issue ?

Thank you !

**Comment by dleslie** [comment]
I have the same device and CUPS printing seems to be working fine for me.

```
e78403d8a4e7262892532b66041b357dc68b0cc7

Linux 6.1.0-28-amd64

#> dpkg -l | grep cups
ii  cups                                             2.4.2-3+deb12u8                           amd64        Common UNIX Printing System(tm) - PPD/driver support, web interface
ii  cups-browsed                                     1.28.17-3+deb12u1                         amd64        OpenPrinting CUPS Filters - cups-browsed
ii  cups-client                                      2.4.2-3+deb12u8                           amd64        Common UNIX Printing System(tm) - client programs (SysV)
ii  cups-common                                      2.4.2-3+deb12u8                           all          Common UNIX Printing System(tm) - common files
ii  cups-core-drivers                                2.4.2-3+deb12u8                           amd64        Common UNIX Printing System(tm) - driverless printing
ii  cups-daemon                                      2.4.2-3+deb12u8                           amd64
```
